### ISSUE TITLE
Bot crash after repeated deaths

### ISSUE THREAD

**Issue by ProfessorQu** [azalea-rs/azalea#136]
Every once in a while when I am bullying my bot by killing it over and over again I get this error:
> thread 'tokio-runtime-worker' panicked at C:\Users\user\.cargo\git\checkouts\azalea-cdffe42e9d507c39\7fc31f9\azalea-physics\src\collision\world_collisions.rs:18:62:
> called `Option::unwrap()` on a `None` value
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Encountered a panic in system `azalea_physics::travel`!
> tick_run_schedule_loop error: channel closed
> thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at ' panicked at C:\Users\user\.cargo\git\checkouts\azalea-cdffe42e9d507c39\7fc31f9\azalea-client\src\chat.rsC:\Users\user\.cargo\git\checkouts\azalea-cdffe42e9d507c39\7fc31f9\azalea-client\src\chat.rs:thread ':174tokio-runtime-worker174:' panicked at :43C:\Users\user\.cargo\git\checkouts\azalea-cdffe42e9d507c39\7fc31f9\azalea-client\src\chat.rs43:
> ::
> called `Result::unwrap()` on an `Err` value: SendError { .. }174called `Result::unwrap()` on an `Err` value: SendError { .. }
> :
> 43:
> called `Result::unwrap()` on an `Err` value: SendError { .. }
> error: process didn't exit successfully: `target\debug\Bot.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)

It seems to be about [this line of code](https://github.com/azalea-rs/azalea/blob/7fc31f9506df8a0ad532741576473aedd13786b1/azalea-physics/src/collision/world_collisions.rs#L18C5-L18C71). I only get this sometimes when I kill my bot like 4+ times. It also, as seen in the error, crashes the program stopping the bot from running.

**Comment by 1zun4** [comment]
Similiar to https://github.com/azalea-rs/azalea/issues/151 but another point of failure. azalea often makes use of unwrap causing the whole program to panic.

**Comment by mat-1** [comment]
Fixed in https://github.com/azalea-rs/azalea/commit/8808ecef9416edca9c77296742a533e848fba075
