### ISSUE TITLE
suggestions for code

### ISSUE THREAD

**Issue by kittenvr** [azalea-rs/azalea#144]
here are some ideas for things to do all of these should have a minimum of 5 bots

- stalker
- protect
- worldedit
- litematica
# worledit 
just the worledit selection that you input on the client and the do like set dirt
# stalker 
chill at build limit at spawn follow players above build limit 250 blocks around spawn steal shulker and put in ender chest
# protect 
above build limit above player if player gets attacked come down and attack attacker or if the player attacks someone

**Comment by mat-1** [comment]
azalea is a library for making bots. these are interesting ideas for bots that you could make, but imo they're out of scope for azalea itself.

**Comment by kittenvr** [comment]
> azalea is a library for making bots. these are interesting ideas for bots that you could make, but imo they're out of scope for azalea itself.

where could i post ideas like this?
