### ISSUE TITLE
Supported Minecraft version should be more apparent on crates.io

### ISSUE THREAD

**Issue by taitep** [azalea-rs/azalea#170]
Im trying to make a simple working bot (using the echo example), but when i try to connect the bot to my LAN game (which is Fabric 1.21.1) it gives me the following log message: `Error joining as BOT: Disconnected: Incompatible client! Please use 1.21.1. Waiting 15s and trying again.`
This happens both with offline and microsoft accounts. I am using the latest azalea version from crates.io. My game has no server side mods that would be required on the client as well, a vanilla client should be able to connect no problem.

**Comment by taitep** [comment]
This issue also occurs on PaperMC, this is certainly not a fabric related issue.

**Comment by veronoicc** [comment]
If im thinking correctly https://docs.rs/azalea-protocol/0.9.1/azalea_protocol/packets/constant.PROTOCOL_VERSION.html should be the wiki link for the crates.io version, which is protocol 765 aka 1.20.3-4

**Comment by veronoicc** [comment]
If you need 1.21.1, you should be using the version from this github using a git dependency as of right now, as it is made for protocol 767 (https://docs.rs/azalea-protocol/0.9.1/azalea_protocol/packets/constant.PROTOCOL_VERSION.html 1.21-1 i believe)

**Comment by taitep** [comment]
Oh, i think it should then be clearer on crates.io that that version is not for 1.21. Thats the only issue, i saw 1.21.1 on the github readme and it said nothing else on crates.io so i thought that was the latest version.

**Comment by mat-1** [comment]
I added the Minecraft version to the crate version on crates.io (latest one is `v0.10.3+mc1.21.1`), hopefully this makes it clear enough.
