### ISSUE TITLE
Whisper message is wrong

### ISSUE THREAD

**Issue by ozaner** [azalea-rs/azalea#173]
When printing a whisper chat message from some player to the client (via the `message` fn), it prints:
`You whisper to {player}: {message}`

It should be:
`{player} whispers to you: {message}`

For a minimal code example that displays this, just use the example from the README:
```rust
//...

#[derive(Default, Clone, Component)]
pub struct State {}

async fn handle(bot: Client, event: Event, state: State) -> anyhow::Result<()> {
    match event {
        Event::Chat(m) => {
            println!("{}", m.message().to_ansi());
        }
        _ => {}
    }

    Ok(())
}
```

**Comment by ozaner** [comment]
Looked into it a bit more and it seems the language string for `en_us` is correct:

[azalea-language/src/en_us.json L2594](https://github.com/azalea-rs/azalea/blob/2992fc6b4793e00cb35568e6bc42f7bde02463dd/azalea-language/src/en_us.json#L2594):
```
  "commands.message.display.incoming": "%s whispers to you: %s",
  "commands.message.display.outgoing": "You whisper to %s: %s",
```

The `message` fn itself is also correctly calls `chat_translation_key` which maps the chat types correctly:

[azalea-protocol/src/packets/game/clientbound_player_chat_packet.rs#L129](https://github.com/azalea-rs/azalea/blob/2992fc6b4793e00cb35568e6bc42f7bde02463dd/azalea-protocol/src/packets/game/clientbound_player_chat_packet.rs#L129)
```rust
//...
ChatType::MsgCommandIncoming => "commands.message.display.incoming"
ChatType::MsgCommandOutgoing => "commands.message.display.outgoing",
//...
```

The only thing I can think of is either:
1. The Id numbers for the different chat numbers is wrong:

See [azalea-protocol/src/packets/game/clientbound_player_chat_packet.rs#L56](https://github.com/azalea-rs/azalea/blob/2992fc6b4793e00cb35568e6bc42f7bde02463dd/azalea-protocol/src/packets/game/clientbound_player_chat_packet.rs#L56)
```rust
pub enum ChatType {
    Chat = 0,
    SayCommand = 1,
    MsgCommandIncoming = 2,
    MsgCommandOutgoing = 3,
    TeamMsgCommandIncoming = 4,
    TeamMsgCommandOutgoing = 5,
    EmoteCommand = 6,
}
```
I couldn't find a source to verify that these numbers are correct.

2. The vanilla Minecraft 1.21.1 client sends the wrong chat type. That must mean the client interprets the message type incorrectly as well, since it displays "{player} whispers to you: {message}" just fine.

**Comment by mat-1** [comment]
I was updating for 1.21.4 and I noticed that yeah, apparently at some point the ChatType IDs were changed so they're all shifted by 1, and 0 is impossible. I'm probably not going to bother fixing it for the current version, but the fix will be merged when the next Minecraft version is released (which is probably gonna be in a couple weeks).
